name: sorted_set
version: 0.2.2
homepage: https://github.com/JosephMoniz/dart-sorted-set
description: >
  An array backed sorted set.
author: Joseph Moniz <joseph.moniz@gmail.com>
dependencies:
  option: '>=0.2.0 <0.3.0'